set nocompatible
set encoding=utf-8
filetype plugin indent on
syntax enable
set hidden
set noloadplugins

" FIXME: only add for devicons specific tests
packadd devicons

let &runtimepath.=',' . fnamemodify(fnamemodify(expand('<script>'), ':h') . '/../', ':p')
runtime! plugin/fuzzbox.vim
runtime! after/plugin/fuzzbox.vim
