name: run-tests
on: [push, pull_request]
jobs:
  linux:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - name: Environment Info
        run: |
          uname -a
          vim --version
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Install Packages
        run: |
          git clone https://github.com/lifepillar/vim-devel.git ~/.vim/pack/devel
          git clone https://github.com/ryanoasis/vim-devicons.git ~/.vim/pack/plugins/opt/devicons
      - name: Test Commands
        run: |
          ./test/run_tests.sh commands_test.vim
      - name: Test Devicons
        run: |
          ./test/run_tests.sh devicons_test.vim

